annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-catalog/kube-prometheus-stack-18.1.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-catalog/kube-prometheus-stack-18.1.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-catalog/kube-prometheus-stack-18.1.0.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-18.1.0.tgz
dateCreated: '2025-09-08T08:37:33.917568Z'
digest: b72fb7952db9bec0c465a8223185b364bf6682f96fc01143d250b3e625f9e214
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
