annotations:
  application.giantswarm.io/team: phoenix
chartApiVersion: v2
chartFile: prometheus-blackbox-exporter-0.9.0.tgz
dateCreated: '2026-07-27T08:38:56.039735Z'
digest: bdcf8569f2b2253b084d2ba82ff148c662bd9f5d2510d3c9b3180321cd4dfb51
home: https://github.com/giantswarm/prometheus-blackbox-exporter-app
icon: https://s.giantswarm.io/app-icons/prometheus/1/light.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
