annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-catalog/kube-prometheus-stack-9.1.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-catalog/kube-prometheus-stack-9.1.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-catalog/kube-prometheus-stack-9.1.0.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: kube-prometheus-stack-9.1.0.tgz
dateCreated: '2024-03-06T15:14:39.320988'
digest: f70fa7f4003c609c4182096f2b1fe1fb4bd7b9d597a6dd5dd5f7833df3ba78e7
home: https://github.com/giantswarm/kube-prometheus-stack-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
