annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-catalog/prometheus-agent-0.3.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-catalog/prometheus-agent-0.3.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  application.giantswarm.io/values-schema: https://giantswarm.github.io/default-catalog/prometheus-agent-0.3.0.tgz-meta/values.schema.json
chartApiVersion: v2
chartFile: prometheus-agent-0.3.0.tgz
dateCreated: '2023-03-22T13:25:16.847485'
digest: 863e724141b29e2485b161f928e897ed822dd6d0d217e0eaa39c9c8baca86d59
home: https://github.com/giantswarm/prometheus-agent-app
restrictions:
  clusterSingleton: true
