annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-catalog/prometheus-operator-app-1.0.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-catalog/prometheus-operator-app-1.0.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  artifacthub.io/links: "- name: Chart Source\n  url: https://github.com/prometheus-community/helm-charts\n\
    - name: Upstream Project\n  url: https://github.com/prometheus-operator/kube-prometheus\n"
  artifacthub.io/operator: 'true'
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-operator-app-1.0.0.tgz
dateCreated: '2022-01-20T16:02:55.129092'
digest: 51f76c70c599ad67d1338b22ea3dba83f4aa839a7305d342c4c86d0bdf85d141
home: https://github.com/giantswarm/prometheus-operator-app
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
