annotations:
  application.giantswarm.io/metadata: https://giantswarm.github.io/default-catalog/prometheus-operator-crd-2.0.0.tgz-meta/main.yaml
  application.giantswarm.io/readme: https://giantswarm.github.io/default-catalog/prometheus-operator-crd-2.0.0.tgz-meta/README.md
  application.giantswarm.io/team: atlas
  config.giantswarm.io/version: 1.x.x
chartApiVersion: v2
chartFile: prometheus-operator-crd-2.0.0.tgz
dateCreated: '2022-10-20T15:45:24.470327'
digest: 9378f9b470749f0a25651c12d212fe3b59c047a4a144e279173ee26810b06844
home: https://github.com/giantswarm/prometheus-operator-crd
icon: https://s.giantswarm.io/app-icons/prometheus-operator/2/light.svg
restrictions:
  clusterSingleton: true
